AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  NewCops: enable
  SuggestExtensions: false

Layout/EndOfLine:
  EnforcedStyle: lf
Style/OptionalBooleanParameter:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Layout/EndAlignment:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 15
