# SPDX-FileCopyrightText: Copyright (c) 2019 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  pdd -f /dev/null
  bundle install --no-color
release:
  pre: false
  script: |-
    bundle exec rake clean test rubocop copyright
    sed -i "s/0\.0\.0/${tag}/g" obk.gemspec
    git add obk.gemspec
    git commit -m "version set to ${tag}"
    gem build obk.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake clean test rubocop copyright
